# Generated by Django 6.0 on 2025-12-04 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlocksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('faq', 5), ('testimonial', 8), ('cta', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('name', 1), ('role', 6), ('photo', 7), ('quote', 2)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Learn more', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('heading', 1), ('text', 2), ('button_text', 9), ('button_link', 10)]], {})})),
            ],
            options={
                'verbose_name': 'Custom Blocks Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
